version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          playwright install
          playwright install chrome
      - run:
          name: Run tests
          command: |
            mkdir test-results
            python -m pytest --template=html1/index.html --report=test-results/report.html
      - store_artifacts:
          path: test-results

workflows:
  test_my_app:
    jobs:
      - build_and_test
